// ================================================================
// Combined single-file drawBbox.v
// Generated by merging: drawBbox.v + threshold.v + polarity.v + ccl.v + boxing.v
// Note: original `include directives are removed because all modules are in this file.
// ================================================================


// ================================================================
// Source: drawBbox.v
// ================================================================


module drawBbox (
    input      clk,
    input      rst,
    input      enable,
    output     done,

    // ImgROM
    input      [31:0] Img_Q,
    output            Img_CEN,
    output reg [15:0] Img_A,

    // UrSRAM
    input       [31:0] Ur_Q,
    output             Ur_CEN,
    output             Ur_WEN,
    output      [15:0] Ur_A,
    output      [31:0] Ur_D,

    // AnsSRAM
    input      [31:0] Ans_Q,
    output            Ans_CEN,
    output            Ans_WEN,
    output     [31:0] Ans_D,
    output     [15:0] Ans_A
);

// ==========================================
// 頂層主控狀態機 (Top-level FSM)
// ==========================================
localparam ST_IDLE  = 3'd0;
localparam ST_THRES = 3'd1;
localparam ST_POL   = 3'd2;
localparam ST_CCL   = 3'd3;
localparam ST_BOX   = 3'd4;


wire box_done;
reg [2:0] state, next_state;

always @(posedge clk or posedge rst) begin
    if (rst) state <= ST_IDLE;
    else     state <= next_state;
end






// ==========================================
// 階段 1: Threshold
// ==========================================
wire [7:0] threshold;
wire thres_done;
wire thres_img_cen;
wire [15:0] thres_img_addr;
wire thres_ur_cen;
wire thres_ur_wen;
wire [15:0] thres_ur_a;
wire [31:0] thres_ur_d;

threshold thres(
    .clk(clk),
    .rst(rst),
    .start(enable), // 完美接收 1-cycle 的 enable
    .Threshold(threshold),
    .done(thres_done),

    .Img_Q(Img_Q),
    .Img_CEN(thres_img_cen),
    .Img_addr(thres_img_addr),

    .Ur_Q(Ur_Q),
    .Ur_CEN(thres_ur_cen),
    .Ur_WEN(thres_ur_wen),
    .Ur_A(thres_ur_a),
    .Ur_D(thres_ur_d)
);

// ==========================================
// 階段 2: Polarity
// ==========================================
wire pol_done;
wire pol_flag;
wire pol_img_cen;
wire pol_img_wen;
wire [15:0] pol_img_addr;

polarity u_polarity(
    .clk(clk),
    .rst(rst),
    .valid(thres_done), // 完美接收 1-cycle 脈衝
    .threshold(threshold),

    .Img_Q(Ur_Q),
    .Img_CEN(pol_img_cen),
    .Img_A(pol_img_addr),
    .Img_WEN(pol_img_wen),

    .done(pol_done),
    .polarity(pol_flag)
);

// ==========================================
// 階段 3: CCL (Labeler)
// ==========================================
wire ccl_done;
wire ccl_img_cen;
wire ccl_img_wen;
wire [15:0] ccl_img_addr;
wire [9:0] total_label;

wire ccl_ans_cen;
wire ccl_ans_wen;
wire [15:0] ccl_ans_addr;
wire [31:0] ccl_ans_d;

ccl u_ccl(
    .clk(clk),
    .rst(rst),
    .threshold(threshold),
    .labeler_en(pol_done),
    .polarity(pol_flag),

    .img_cen(ccl_img_cen),
    .img_addr(ccl_img_addr),
    .img_wen(ccl_img_wen),
    .img_Q(Ur_Q),

    .ans_cen(ccl_ans_cen),
    .ans_wen(ccl_ans_wen),
    .ans_addr(ccl_ans_addr),
    .ans_D(ccl_ans_d),
    .ans_Q(Ans_Q),


    .labeler_done(ccl_done),
    .total_label(total_label)
);

// ==========================================
// 階段 4: Boxing
// ==========================================
wire box_img_cen;
wire [15:0] box_img_addr;

wire box_ans_cen;
wire box_ans_wen;
wire [15:0] box_ans_addr;
wire [31:0] box_ans_d;

boxing u_boxing(
    .clk(clk),
    .rst(rst),
    .enable(ccl_done),
    .done(box_done), // 連接到頂層的 done
    .total_label(total_label),

    .Img_Q(Img_Q),
    .Img_CEN(box_img_cen),
    .Img_A(box_img_addr),

    .Ans_Q(Ans_Q),
    .Ans_CEN(box_ans_cen),
    .Ans_WEN(box_ans_wen),
    .Ans_D(box_ans_d),
    .Ans_A(box_ans_addr)
);

// ==========================================
// 根據「狀態」優雅分配記憶體權限
// ==========================================

// --- 1. ImgROM (彩色原圖) ---
assign Img_CEN = (state == ST_THRES) ? thres_img_cen :
                 (state == ST_BOX)   ? box_img_cen   : 1'b1;

always @(*) begin
    if      (state == ST_THRES) Img_A = thres_img_addr;
    else if (state == ST_BOX)   Img_A = box_img_addr;
    else                        Img_A = 16'd0;
end

// --- 2. UrSRAM (灰階暫存區) ---
assign Ur_CEN  = (state == ST_THRES) ? thres_ur_cen :
                 (state == ST_POL)   ? pol_img_cen  :
                 (state == ST_CCL)   ? ccl_img_cen  : 1'b1;

assign Ur_WEN  = (state == ST_THRES) ? thres_ur_wen : 1'b1;

assign Ur_A    = (state == ST_THRES) ? thres_ur_a   :
                 (state == ST_POL)   ? pol_img_addr :
                 (state == ST_CCL)   ? ccl_img_addr : 16'd0;

assign Ur_D    = (state == ST_THRES) ? thres_ur_d   : 32'd0;

// --- 3. AnsSRAM (標籤與最終成圖區) ---
assign Ans_CEN = (state == ST_CCL) ? ccl_ans_cen  :
                 (state == ST_BOX) ? box_ans_cen  : 1'b1;

assign Ans_WEN = (state == ST_CCL) ? ccl_ans_wen  :
                 (state == ST_BOX) ? box_ans_wen  : 1'b1;

assign Ans_A   = (state == ST_CCL) ? ccl_ans_addr :
                 (state == ST_BOX) ? box_ans_addr : 16'd0;

assign Ans_D   = (state == ST_CCL) ? ccl_ans_d    :
                 (state == ST_BOX) ? box_ans_d    : 32'd0;


always @(*) begin
    case (state)
        ST_IDLE:  if (enable)     next_state = ST_THRES; else next_state = ST_IDLE;
        ST_THRES: if (thres_done) next_state = ST_POL;   else next_state = ST_THRES;
        ST_POL:   if (pol_done)   next_state = ST_CCL;   else next_state = ST_POL;
        ST_CCL:   if (ccl_done)   next_state = ST_BOX;   else next_state = ST_CCL;
        ST_BOX:   if (box_done)   next_state = ST_IDLE;  else next_state = ST_BOX;
        default:  next_state = ST_IDLE;
    endcase
end
assign done = box_done; // 把 boxing 的完成訊號直接交給 Testbench
//assign done = ccl_done;

endmodule

// ================================================================
// Source: threshold.v
// ================================================================

module threshold (
    input      clk,
    input      rst,
    input      start,   //啟動時拉高一個clk周期
    output [7:0] Threshold, //輸出threshold值
    output reg done,    //完成後拉高

    // ImgROM
    input      [31:0] Img_Q,
    output            Img_CEN, //active low
    output reg [15:0] Img_addr,

    // UrSRAM
    input       [31:0] Ur_Q,
    output             Ur_CEN,
    output             Ur_WEN,
    output      [15:0] Ur_A,
    output      [31:0] Ur_D
);
reg [3:0] state;

reg [15:0]  counter;
wire[16:0]  next_counter;
assign next_counter = counter + 16'b1;
integer i;//迴圈變數
reg Img_cen;
assign Img_CEN = Img_cen;
reg Ur_wen;
assign Ur_WEN = Ur_wen;
reg Ur_cen;
assign Ur_CEN = Ur_cen;
reg [15:0] Ur_addr;
assign Ur_A = Ur_addr;
reg [31:0] Ur_d;
assign Ur_D = Ur_d;
//灰階
wire [25:0] image_gray_before_round;
wire [7:0] image_gray_after_round;  //灰階最高256，8bit存儲wire round_up;
wire round_up = (image_gray_before_round[15:0] > 16'h8000) ||
                  ((image_gray_before_round[15:0] == 16'h8000) && (image_gray_before_round[16] == 1'b1)); //判斷是否需要進行四捨五入，根據小數部分的值來決定是否將整數部分加1。
assign image_gray_before_round = (26'd19595 * Img_Q[23:16]) +
                                 (26'd38470 * Img_Q[15:8])  +
                                 (26'd7471  * Img_Q[7:0]); // 公式為 (0.299*R + 0.587*G + 0.114*B)這裡先乘以256以保留小數部分，最後再除以256進行四捨五入。
assign image_gray_after_round = round_up ? (image_gray_before_round[23:16] + 8'd1) :
                                           (image_gray_before_round[23:16]);

//高斯
reg [7:0] u1, u2, u3, m1, m2, m3, b1, b2, b3;    //input
wire [15:0] gaussian_sum = (u1) + (u2<<1) + (u3) +
                             (m1<<1) + (m2<<2) + (m3<<1) +
                             (b1) + (b2<<1) + (b3);   //取四位小數
wire gaussian_round_up = (gaussian_sum[3:0] > 4'b1000) ||
                         ((gaussian_sum[3:0] == 4'b1000) && (gaussian_sum[4] == 1'b1)); //判斷是否需要進行四捨五入，根據小數部分的值來決定是否將整數部分加1。
wire [7:0] gaussian_value = gaussian_round_up ? (gaussian_sum[11:4] + 8'd1) : (gaussian_sum[11:4]);

wire Is_the_most_up = (counter[15:8] == 8'd0)?1'b1:1'b0;
wire Is_the_most_buttom = (counter[15:8] == 8'd255)?1'b1:1'b0;
wire Is_the_most_left = (counter[7:0] == 8'd0)?1'b1:1'b0;
wire Is_the_most_right = (counter[7:0] == 8'd255)?1'b1:1'b0;
//計算高斯數據參數
reg [3:0]get_data_state;
wire [4:0]next_get_data_state = (get_data_state == 4'd11)? 4'b0 : (get_data_state + 4'b1);
wire[15:0]up_index = counter - 16'd256;
wire[15:0]buttom_index = counter + 16'd256;

//分類前景後景參數
reg [1:0] ISODATA_state ;
reg [15:0] gray_level[255:0];  //灰階值
wire [16:0] next_gray_level = gray_level[gaussian_value] + 16'b1;

reg [23:0] sum_contribution_background;    //65536*256最大值為16777216，需要24bit來存儲
wire [24:0] next_sum_contribution_background;
assign next_sum_contribution_background = sum_contribution_background + (gray_level[counter]*counter);
reg [23:0] sum_contribution_foreground;
wire [24:0] next_sum_contribution_foreground;
assign next_sum_contribution_foreground = sum_contribution_foreground + (gray_level[counter]*counter);
//計算threshold用
reg [15:0] sf;
wire [16:0] next_sf = sf + gray_level[counter];
reg [15:0] sb;
wire [16:0] next_sb = sb + gray_level[counter];

reg [7:0] T_counter;
wire [8:0] next_T_counter = (T_counter == 0)? 8'b0 : T_counter - 8'b1;
wire [40:0] term_f = sum_contribution_foreground * sb; // 24bit*17bit=41bit
wire [40:0] term_b = sum_contribution_background * sf; // 24bit*17bit=41bit

// 計算分子,絕對差值的平方
wire [40:0] diff_term = (term_f > term_b) ? (term_f - term_b) : (term_b - term_f);
wire [81:0] num_curr  = diff_term * diff_term; // 41-bit * 41-bit = 82-bit

// 計算分母
wire [33:0] den_curr  = sf * sb; // 17-bit * 17-bit = 34-bit

// 交叉相乘
reg [81:0] num_max;
reg [33:0] den_max;
reg [7:0]  Max_T; // 最佳 Threshold 輸出
assign Threshold = Max_T;    //輸出threshold

// 交叉相乘
wire [115:0] cross_left  = num_curr * den_max;
wire [115:0] cross_right = num_max * den_curr;


always@(posedge rst or posedge clk) begin
    if(rst) begin   //初始化
	done <= 1'd0;
        counter <= 16'd0;
        state <= 2'd0;
        Img_cen <= 1'd0;    //預設為讀取圖像
	    Img_addr <= 16'd0;
        Ur_cen <= 1'b0;
        Ur_addr <= 16'd0;
        Ur_d <= 32'd0;

        //gaussian參數初始化
        get_data_state <= 4'd0;
        u1 <= 8'd0;
        u2 <= 8'd0;
        u3 <= 8'd0;
        m1 <= 8'd0;
        m2 <= 8'd0;
        m3 <= 8'd0;
        b1 <= 8'd0;
        b2 <= 8'd0;
        b3 <= 8'd0;

        //分類前景後景參數初始化
        ISODATA_state <= 2'd0;
        for(i = 0; i < 256; i = i + 1) begin
		    gray_level[i] <= 16'b0;
        end
        T_counter <= 8'b0;
        sum_contribution_background <= 24'd0;
        sum_contribution_foreground <= 24'd0;
        sf <= 16'd0;
        sb <= 16'd0;
        Max_T <= 8'd0;

	num_max <= 82'd0;
        den_max <= 34'd0;
    end else if (start && state == 2'd0) begin //初始化不為零的數字
        state <= 2'd1;
        Ur_wen <= 1'b1;
	den_max <= 34'd1; // 分母初始值設為1
    end else if(state == 2'd1) begin   //得到u1~b3
	    if(get_data_state == 0)begin
            	Ur_wen <= 1'b1;	//停止寫入，讀取資料
		Img_addr <= up_index - 16'd1;
	    end else if (get_data_state == 1)begin
		Img_addr <= up_index;
	    end else if(get_data_state == 2)begin   //delay 2 clk拿到數據
		    Img_addr <= up_index + 16'd1;
            	u1 <= image_gray_after_round;
	    end else if(get_data_state == 3)begin
            	Img_addr <= counter - 16'd1;
            u2 <= image_gray_after_round;
	    end else if (get_data_state == 4)begin
			Img_addr <= counter;
            u3 <= image_gray_after_round;
	    end else if(get_data_state == 5)begin   //delay 2 clk拿到數據
		    Img_addr <= counter + 16'd1;
            m1 <= image_gray_after_round;
	    end else if(get_data_state == 6)begin
            Img_addr <= buttom_index - 16'd1;
            m2 <= image_gray_after_round;
	    end else if (get_data_state == 7)begin
			Img_addr <= buttom_index;
            m3 <= image_gray_after_round;
	    end else if(get_data_state == 8)begin   //delay 2 clk拿到數據
		    Img_addr <= buttom_index + 16'd1;
            b1 <= image_gray_after_round;
	    end else if(get_data_state == 9)begin
            b2 <= image_gray_after_round;
	    end else if(get_data_state == 10)begin
            b3 <= image_gray_after_round; //數據取完了
	    end else if(get_data_state == 11)begin      //處理數據
		if(Is_the_most_up && Is_the_most_left) begin    //Reflect 101 padding
                u1 <= b3;  //角
                u3 <= b3;
                b1 <= b3;

                u2 <= b2;   //邊
                m1 <= m3;
            end else if(Is_the_most_up && Is_the_most_right) begin
                u1 <= b1;  //角
                u3 <= b1;
                b3 <= b1;

                u2 <= b2;   //邊
                m3 <= m1;
            end else if(Is_the_most_buttom && Is_the_most_left) begin
                u1 <= u3;  //角
                b1 <= u3;
                b3 <= u3;

                b2 <= u2;   //邊
                m1 <= m3;
            end else if(Is_the_most_buttom && Is_the_most_right) begin
                u3 <= u1;  //角
                b1 <= u1;
                b3 <= u1;

                b2 <= u2;   //邊
                m3 <= m1;
            end else if(Is_the_most_up) begin
                u1 <= b1;
                u2 <= b2;
                u3 <= b3;
            end else if(Is_the_most_buttom) begin
                b1 <= u1;
                b2 <= u2;
                b3 <= u3;
            end else if(Is_the_most_left) begin
                u1 <= u3;
                m1 <= m3;
                b1 <= b3;
            end else if(Is_the_most_right) begin
                u3 <= u1;
                m3 <= m1;
                b3 <= b1;
            end
		    state <= 2'd2; //在wire把高斯做出來(gaussian_value)，把結果寫進reg
        end
		get_data_state <= next_get_data_state[3:0];
    end else if(state == 2'd2) begin   //高斯寫入
        Ur_wen <= 0;	//允許寫入
	Ur_addr <= counter;
        Ur_d <= {24'b0, gaussian_value}; //高斯值寫入SRAM

        gray_level[gaussian_value] <= next_gray_level[15:0]; //統計灰階值的分布(下個階段會用到)

	    if(counter == 16'd65535)begin   //結束了
		counter <= 16'b0;   //counter歸零
        	state <= 2'd3; //下一階段
		T_counter <= 255;
	    end else begin
		counter <= next_counter[15:0];
        	state <= 2'd1;  //回到state 1繼續取數據
	    end
    end else if(state == 2'd3) begin   //分前景後景
        if(ISODATA_state == 2'd0)begin  //初始化
	    Ur_wen <= 1;
            T_counter <= next_T_counter[7:0]; //threshold為255不用計算，第一次就從254開始
            sum_contribution_background <= 24'b0;
            sum_contribution_foreground <= 24'b0;
            sf <= 16'd0;
            sb <= 16'd0;
            ISODATA_state <= 2'd1;
        end else if(ISODATA_state == 2'd1)begin //找新的閾值
            if(counter[7:0] > T_counter) begin //前景
                sum_contribution_foreground <= next_sum_contribution_foreground[23:0]; //前景的灰階值總和
                sf <= next_sf[15:0]; //前景的像素數量
            end else begin //背景
		sum_contribution_background <= next_sum_contribution_background[23:0]; //背景的灰階值總和
                sb <= next_sb[15:0]; //背景的像素數量
            end

	        if(counter == 16'd255)begin
        	    ISODATA_state <= 2'd2;
		        counter <= 16'd0;
	        end else begin
		        counter <= next_counter[15:0];
	        end
        end else if(ISODATA_state == 2'd2)begin
		if (cross_left >= cross_right && cross_left) begin
            		num_max <= num_curr; // 更新最大分子
            		den_max <= den_curr; // 更新最大分母
            		Max_T   <= T_counter; // 記錄對應的 Threshold
        	end
		if(T_counter == 8'd0)begin //完成
                    state <= 2'd0; //停止
		    counter <= 0;
		    done <= 1'b1;
                end else begin
                    ISODATA_state <= 2'd0; //還沒完成，繼續找下一個threshold
                end
        end
    end
end
endmodule

// ================================================================
// Source: polarity.v
// ================================================================

module polarity(
    input clk,rst,
    input valid,
    input [7:0] threshold,

    // ImgROM
    input [31:0] Img_Q,
    output reg Img_CEN,
    output reg [15:0] Img_A,
    output Img_WEN,

    output reg done,
    output reg polarity // 0: amount less than thres is foreground
                    // 1: amount more than thres is foreground
);

    assign Img_WEN = 1'b1;

    reg [7:0] counter;
    reg [1:0] cs,ns;
    reg proc_done;

    localparam IDLE = 2'b00;
    localparam PROCESS = 2'b01;
    localparam DONE = 2'b10;

    always@(posedge clk or  posedge rst)begin
        if(rst)begin
            cs <= IDLE;
        end else begin
            cs <= ns;
        end
    end

    always@(*)begin
        case(cs)
            IDLE:begin
                if(valid) ns = PROCESS;
                else ns = IDLE;
            end
            PROCESS:begin
                if(proc_done) ns = DONE;
                else ns = PROCESS;
            end
            DONE:begin
                ns = DONE;
            end
            default: ns = IDLE;
        endcase
    end

    reg process_start,process_start_d;

    always@(posedge clk or posedge rst)begin
        if(rst)begin
            process_start_d <= 1'b0;
        end else begin
            process_start_d <= process_start;
        end
    end

    always@(posedge clk or posedge rst)begin
        if(rst)begin
            counter <= 8'd0;
            Img_CEN <= 1'b0;
            Img_A <= 16'd0;
            process_start <= 1'b0;
            polarity <= 1'b0;
            proc_done <= 1'b0;
        end else begin
            case(cs)
                IDLE:begin
                    counter <= 8'd0;
                    Img_CEN <= 1'b1;
                    Img_A <= 16'd0;
                    process_start <= 1'b0;
                    polarity <= 1'b0;
                    proc_done <= 1'b0;
                    done <= 1'b0;
                end
                PROCESS:begin
                    process_start <= 1'b1;
                    if(process_start_d)begin
                        if((Img_Q >= threshold) && (counter < 8'd255)) counter <= counter + 8'd1;
                    end
                    if(!Img_A[8])begin
                        Img_CEN <= 1'b0;
                        Img_A <= Img_A + 16'd1;
                    end else begin
                        proc_done <= 1'b1;
                    end
                end
                DONE:begin
                    if(counter >= 8'd128) polarity <= 1'b0;
                    else polarity <= 1'b1;
                    done <= 1'b1;
                end
            endcase
        end
    end
endmodule

// ================================================================
// Source: ccl.v
// ================================================================

module ccl(
    input clk,
    input rst,
    input [7:0] threshold,
    input labeler_en, // to turn on labeler
    input polarity,

    // ImgRom (Read)
    output reg img_cen, // to read ImgRom
    output reg [15:0] img_addr,
    output  img_wen,
    input [31:0] img_Q,

    // AnsSRAM (Read & Write)
    output reg ans_cen, // turn on SRAM
    output reg ans_wen, // to write SRAM
    output reg [15:0] ans_addr,
    output reg [31:0] ans_D,
    input [31:0] ans_Q,

    output reg labeler_done,
    output [9:0] total_label
);
reg [9:0] consecutive_label;
assign total_label = consecutive_label - 10'd1;
assign img_wen = 1'b1;
// 0: amount less than thres is foreground
// 1: amount more than thres is foreground
reg pol;
// polarity
always@(posedge clk or posedge rst)begin
    if(rst)begin
        pol<= 1'b0;
    end else if(labeler_en)begin
        pol <= polarity;
    end
end
wire [31:0] bin_img_Q_light,bin_img_Q_dark,bin_img_Q;
assign bin_img_Q_light = (img_Q[7:0] <= threshold)? 32'd1: 32'd0;
assign bin_img_Q_dark = (img_Q[7:0] > threshold)? 32'd1: 32'd0;
assign bin_img_Q = (pol)? bin_img_Q_dark:bin_img_Q_light;

reg [2:0] state, next_state;
localparam IDLE = 3'b000;
localparam READ_PASS_1 = 3'b001;
localparam WRITE_PASS_1 = 3'b010;
localparam FLATTEN_TABLE = 3'b011;
localparam READ_PASS_2 = 3'b100;
localparam WRITE_PASS_2 = 3'b101;
localparam DONE = 3'b110;

always@(posedge clk or posedge rst)begin
    if(rst)begin
        state <= IDLE;
    end else begin
        state <= next_state;
    end
end

reg buffer_done;
reg READ_PASS_1_done;
reg flatten_done;
wire WRITE_PASS_1_read, WRITE_PASS_1_finish;
reg write_pass_2_finish;
reg write_pass_2_done;
reg read_pass_2_done,read_pass_2_done_d;

always@(*)begin
    case(state)
        IDLE:begin
            if(labeler_en) next_state = READ_PASS_1;
            else next_state = IDLE;
        end
        READ_PASS_1:begin
            if(READ_PASS_1_done) next_state = WRITE_PASS_1;
            else next_state = READ_PASS_1;
        end
        WRITE_PASS_1:begin
            if(WRITE_PASS_1_finish) next_state = FLATTEN_TABLE;
            else if(WRITE_PASS_1_read) next_state = READ_PASS_1;
            else next_state = WRITE_PASS_1;
        end
        FLATTEN_TABLE:begin
            if(flatten_done) next_state = READ_PASS_2;
            else next_state = FLATTEN_TABLE;
        end
        READ_PASS_2:begin
            next_state = WRITE_PASS_2;
        end
        WRITE_PASS_2:begin
            if(write_pass_2_finish) next_state = DONE;
            else if(write_pass_2_done) next_state = READ_PASS_2;
            else next_state = WRITE_PASS_2;
        end
        DONE:begin
            next_state = DONE;
        end
        default: next_state = IDLE;
    endcase
end

reg write_done,write_finish;
reg img_cen_d;
reg img_cen_dd;
reg write_done_d;


always@(posedge clk or posedge rst)begin
    if(rst)begin
        write_done_d <= 1'b0;
        img_cen_d <= 1'b0;
img_cen_dd <= 1'b0;
        read_pass_2_done_d <= 1'b0;
    end else begin
        write_done_d <= write_done;
        img_cen_d <= img_cen;
img_cen_dd <= img_cen_d;
        read_pass_2_done_d <= read_pass_2_done;
    end
end

reg [9:0] line_buffer [511:0];
reg [7:0] buffer_count;
reg [9:0] new_label;
reg [15:0] pixel_idx_write;



integer i;
integer j;
integer k;
reg [9:0] label_buffer[255:0];
wire [9:0] neighbor_W = (buffer_count == 8'd0) ? 10'd0 : label_buffer[buffer_count - 8'd1];
//wire [9:0] neighbor_W = (buffer_count == 8'd0) ? 10'd0 : line_buffer[{1'b1,buffer_count - 8'd1}]; // ---------------------
wire [9:0] neighbor_NW = (buffer_count == 8'd0)   ? 10'd0 : line_buffer[{1'b0, buffer_count - 8'd1}];
wire [9:0] neighbor_N  =                                   line_buffer[{1'b0, buffer_count}];
wire [9:0] neighbor_NE = (buffer_count == 8'd255) ? 10'd0 : line_buffer[{1'b0, buffer_count + 8'd1}];
wire [9:0] min_NW_N = (neighbor_NW == 0) ? neighbor_N :
                      (neighbor_N == 0)  ? neighbor_NW :
                      (neighbor_NW < neighbor_N) ? neighbor_NW : neighbor_N;
wire [9:0] min_NE_W = (neighbor_NE == 0) ? neighbor_W :
                      (neighbor_W == 0)  ? neighbor_NE :
                      (neighbor_NE < neighbor_W) ? neighbor_NE : neighbor_W;
wire [9:0] min_neighbor = (min_NW_N == 0) ? min_NE_W :
                          (min_NE_W == 0) ? min_NW_N :
                          (min_NW_N < min_NE_W) ? min_NW_N : min_NE_W;

reg [9:0] eq_table [1023:0];
reg [9:0] flatten_idx;

//assign WRITE_PASS_1_read = (pixel_idx_write[7:0] == 8'd255 && state == WRITE_PASS_1_read)? 1'b1 : 1'b0;
assign WRITE_PASS_1_read = (write_done)? 1'b1 : 1'b0;
assign WRITE_PASS_1_finish = (write_finish)? 1'b1 : 1'b0;
reg [15:0] pass2_addr;
reg [15:0] read_1_pixel;
reg [7:0] buffer_count_read;


always@(posedge clk or posedge rst)begin
    if(rst)begin
        for(i = 0;i<512;i = i+1)begin
            line_buffer[i] <= 10'd0;
        end
        for(j = 0; j<1024; j = j+1)begin
            eq_table[j] <= 0;
        end
        img_cen <= 1'b0;
        img_addr <= 16'b0;
        buffer_count <= 8'd0;
        new_label <= 10'd0;
        pixel_idx_write <= 16'd0;
        write_done <= 1'b0;
        write_finish <= 1'b0;
        flatten_idx <= 10'd0;
        ans_addr <= 16'd0;
        write_pass_2_done <= 1'b0;
        write_pass_2_finish <= 1'b0;
        consecutive_label <= 10'd0;
        ans_wen <= 1'b0;
        ans_cen <= 1'b0;
        ans_D <= 32'd0;
        labeler_done <= 1'b0;
        buffer_done <= 1'b0;
        flatten_done <= 1'b0;
        READ_PASS_1_done <= 1'b0;
        read_pass_2_done <= 1'b0;
        pass2_addr <= 16'd0;
read_1_pixel <= 16'd0;
buffer_count_read <= 8'd0;
 for(k = 0; k<256; k = k+1)begin
                    label_buffer[k] <= 10'd0;
                end
    end else begin
        case(state)
            IDLE:begin
                for(i = 0;i<512;i = i+1)begin
                    line_buffer[i] <= 10'd0;
                end
                for(j = 0; j<1024; j = j+1)begin
                    eq_table[j] <= j;
                end
                for(k = 0; k<256; k = k+1)begin
                    label_buffer[k] <= 10'd0;
                end
                img_cen <= 1'b1;
                img_addr <= 16'd0;
                new_label <= 10'd1;
                buffer_count <= 8'd0;
                pixel_idx_write <= 16'd0;
                write_done <= 1'b0;
                write_finish <= 1'b0;
                flatten_idx <= 10'd1;
                ans_addr <= 16'd0;
                write_pass_2_done <= 1'b0;
                write_pass_2_finish <= 1'b0;
                consecutive_label <= 10'd1;
                ans_wen <= 1'b1;
                ans_cen <= 1'b1;
                ans_D <= 32'd0;
                labeler_done <= 1'b0;
                buffer_done <= 1'b0;
                flatten_done <= 1'b0;
                READ_PASS_1_done <= 1'b0;
                read_pass_2_done <= 1'b0;
                pass2_addr <= 16'd0;
read_1_pixel <= 16'd0;
buffer_count_read <= 8'd0;
            end
            READ_PASS_1:begin
                if(write_done_d) begin
                    pixel_idx_write <= pixel_idx_write + 16'd1;
                    for(j = 0;j < 256; j = j+1)begin
                        line_buffer[j] <= label_buffer[j];
                        //line_buffer[j] <= line_buffer[j+256]; // -----------------------
                    end
                end else begin
                    img_cen <= 1'b0;
                    img_addr <= read_1_pixel;
                    if(read_1_pixel[7:0] < 8'd255)read_1_pixel <= read_1_pixel + 16'd1;
                    //if(img_addr[7:0] < 8'd255)img_addr <= img_addr + 16'd1;
                    // input img (waiting two clock let the signal in)
                    // start from row1 of buffer because the first row of picture would all be 0
                    if(!img_cen_d)begin
                        if(buffer_count_read < 8'd255)begin
                            line_buffer[{1'b1,buffer_count_read}] <= bin_img_Q;
                            buffer_count_read <= buffer_count_read + 8'd1;
                            READ_PASS_1_done <= 1'b0;
                        end else begin
                            line_buffer[{1'b1,8'd255}] <= bin_img_Q;
                            READ_PASS_1_done <= 1'b1;
                            buffer_count <= 8'd0;
                        end
                    end
                end
            end
            WRITE_PASS_1:begin
                if(READ_PASS_1_done)begin
                    buffer_count_read <= 8'd0;
                    READ_PASS_1_done <= 1'b0;
                    img_cen <= 1'b1;
                end else begin
                    if(buffer_done)begin
                        buffer_count <= 8'd0;
                        ans_wen <= 1'b0;
                        ans_cen <= 1'b0;
                        ans_addr <= pixel_idx_write;
                        ans_D <= {22'd0, label_buffer[pixel_idx_write[7:0]]};
                        //ans_D <= {22'd0, line_buffer[pixel_idx_write[7:0]]}; // ---------------
                        if(pixel_idx_write[7:0] < 8'd255)begin
                            pixel_idx_write <= pixel_idx_write + 16'd1;
                        end else begin
                            write_done <= 1'b1;
                            buffer_done <= 1'b0;
                            read_1_pixel <= read_1_pixel + 16'd1;
                            //buffer_count <= 8'd0;
                        end
                        if(ans_addr == 16'd65535)begin
                            write_finish<= 1'b1;
                            ans_wen <= 1'b1;
                        end
                    end else if (write_done) begin
                        // 🛑 終極解藥：捕捉幽靈週期！ 🛑
                        // 當硬體準備切換到 READ_PASS_1 時，會有一拍的延遲掉進這裡。
                        // 我們在這裡把 write_done 降下來，並且「不執行任何 CCL 運算」，保護 eq_table！
                        write_done <= 1'b0;
                    end else if (!write_finish) begin
                        ans_wen <= 1'b1;
                        ans_cen <= 1'b1;
                        write_done <= 1'b0;
                        // neighbor are all 0, so give it a new label
                        if(line_buffer[{1'b1,buffer_count}])begin
                            if(!neighbor_N && !neighbor_NE && !neighbor_NW && !neighbor_W)begin
                                label_buffer[buffer_count] <= new_label;
                                //line_buffer[buffer_count] <= new_label; // -------------
                                //line_buffer[{1'b1,buffer_count}] <= new_label;
                                new_label <= new_label + 10'd1;
                            // neighbor at least one is nonzero, so give it the smallest label, and equive all nonzero label
                            end else begin
                                //line_buffer[{1'b1, buffer_count}] <= min_neighbor;
                                label_buffer[buffer_count] <= min_neighbor;
                                //line_buffer[buffer_count] <= min_neighbor; // ---------------------
                                /*if (neighbor_W  != 0 && neighbor_W  != min_neighbor) eq_table[neighbor_W]  <= min_neighbor;
                                if (neighbor_NW != 0 && neighbor_NW != min_neighbor) eq_table[neighbor_NW] <= min_neighbor;
                                if (neighbor_N  != 0 && neighbor_N  != min_neighbor) eq_table[neighbor_N]  <= min_neighbor;
                                if (neighbor_NE != 0 && neighbor_NE != min_neighbor) eq_table[neighbor_NE] <= min_neighbor;*/
                                // ✨ 終極完全體：保護樹根的 Heuristic 合併法
                                if (neighbor_W  != 0 && neighbor_W  != min_neighbor) eq_table[eq_table[neighbor_W]]  <= min_neighbor;
                                if (neighbor_NW != 0 && neighbor_NW != min_neighbor) eq_table[eq_table[neighbor_NW]] <= min_neighbor;
                                if (neighbor_N  != 0 && neighbor_N  != min_neighbor) eq_table[eq_table[neighbor_N]]  <= min_neighbor;
                                if (neighbor_NE != 0 && neighbor_NE != min_neighbor) eq_table[eq_table[neighbor_NE]] <= min_neighbor;
                            end
                        end else begin
                            //line_buffer[buffer_count] <= 10'd0; // ------------------------
                            label_buffer[buffer_count] <= 10'd0;
                        end
                        if(buffer_count < 8'd255)begin
                            //buffer_done <= 1'b0;
                            buffer_count <= buffer_count + 8'd1;
                        end else begin
                            buffer_done <= 1'b1;
                        end
                    end
                end
            end
            FLATTEN_TABLE:begin
            ans_cen <= 1'b1;
            ans_wen <= 1'b1;
                img_addr <= 16'd0;
                if(flatten_idx < new_label)begin
                    // Situation A : it is a root

                    if (eq_table[flatten_idx] == flatten_idx) begin
                        eq_table[flatten_idx] <= consecutive_label;
                        consecutive_label <= consecutive_label + 16'd1;
                    // Situation B : it points to previous one
                    end else begin
                        eq_table[flatten_idx] <= eq_table[eq_table[flatten_idx]];
                    end
                    flatten_idx <= flatten_idx + 10'd1;
                end else begin
                    flatten_done <= 1'b1;
                end
                ans_addr <= 16'd0;
            end
            READ_PASS_2:begin
                ans_cen <= 1'b0;
                ans_wen <= 1'b1;
                ans_addr <= pass2_addr;
                write_pass_2_done <= 1'b0;
                read_pass_2_done <= 1'b1;
            end
            WRITE_PASS_2:begin
                read_pass_2_done <= 1'b0;
                if(read_pass_2_done_d)begin
                    if(pass2_addr == 16'd65535)begin
                        ans_wen <= 1'b0;
                        ans_cen <= 1'b0;
                        ans_D <= {16'd0, eq_table[ans_Q[15:0]]};
                        write_pass_2_finish <= 1'b1;
                    end else begin
                        ans_wen <= 1'b0;
                        ans_cen <= 1'b0;
                        pass2_addr <= pass2_addr + 16'd1;
                        ans_D <= {16'd0, eq_table[ans_Q[15:0]]};
                        write_pass_2_done <= 1'b1;
                    end
                end
            end
            DONE:begin
                ans_cen <= 1'b1;
                ans_wen <= 1'b1;
                labeler_done<= 1'b1;
            end
        endcase
    end
end

endmodule

// ================================================================
// Source: boxing.v
// ================================================================

module boxing(
    input      clk,
    input      rst,
    input      enable,
    output reg    done,
    input [9:0] total_label,

    // ImgROM
    input      [31:0] Img_Q,
    output reg           Img_CEN,
    output reg [15:0] Img_A,

    // AnsSRAM
    input      [31:0] Ans_Q,
    output reg           Ans_CEN,
    output reg           Ans_WEN,
    output reg    [31:0] Ans_D,
    output reg    [15:0] Ans_A
);

reg [15:0] pixel;
reg [7:0] min_x[364:0];
reg [7:0] max_x[364:0];
reg [7:0] min_y[364:0];
reg [7:0] max_y[364:0];
reg scan_done;
reg copy_done,copy_done_d;
reg [8:0] box_count;
reg [2:0] state, next_state;
localparam IDLE = 3'd0;
localparam SCAN = 3'd1;
localparam COPY = 3'd2;
localparam BOXING = 3'd3;
localparam DONE = 3'd4;

reg Img_CEN_d;
reg Ans_CEN_d;
reg [7:0] cur_x ;
reg [7:0] cur_y ;
always@(posedge clk or posedge rst)begin
    if(rst)begin
        Img_CEN_d <= 1'b0;
        Ans_CEN_d <= 1'b0;
    end else begin
        Img_CEN_d <= Img_CEN;
        Ans_CEN_d <= Ans_CEN;
    end
end

reg [2:0] box_state,box_next_state;
localparam BOX_IDLE = 3'd0;
localparam BOX_INITIAL = 3'd1;
localparam BOX_WRITE_1 = 3'd2;
localparam BOX_WRITE_2 = 3'd3;
localparam BOX_WRITE_3 = 3'd4;
localparam BOX_WRITE_4 = 3'd5;
localparam BOX_DONE = 3'd6;

reg [7:0] pixel_x, pixel_y;
reg box_write_1_done,box_write_3_done,box_write_4_done;
reg boxing_done;
reg [15:0] read_pixel;

integer i;
integer j;
always@(posedge clk or posedge rst)begin
    if(rst)begin
        Img_CEN <= 1'b0;
        Img_A <= 16'd0;
        Ans_CEN <= 1'b0;
        Ans_WEN <= 1'b0;
        Ans_D <= 32'd0;
        Ans_A <= 16'd0;
        pixel <= 16'd0;
        for(i = 0; i < 365; i = i+1)begin
            min_x[i] <= 8'd0;
            max_x[i] <= 8'd0;
            min_y[i] <= 8'd0;
            max_y[i] <= 8'd0;
        end
        cur_x <= 8'd0;
        cur_y <= 8'd0;
        scan_done <= 1'b0;
        copy_done <= 1'b0;
        copy_done_d <= 1'b0;
        box_count <= 10'd0;
        pixel_x <= 8'd0;
        pixel_y <= 8'd0;
        box_write_1_done <= 1'b0;
        //box_write_2_done <= 1'b0;
        box_write_3_done <= 1'b0;
        box_write_4_done <= 1'b0;
        done <= 1'b0;
        boxing_done <= 1'b0;
        read_pixel <= 16'd0;
    end else begin
        case(state)
            IDLE:begin
                Img_CEN <= 1'b1;
                Img_A <= 16'd0;
                Ans_CEN <= 1'b1;
                Ans_WEN <= 1'b1;
                Ans_D <= 32'd0;
                Ans_A <= 16'd0;
                pixel <= 16'd0;
                for(j = 0; j < 365; j = j+1)begin
                    min_x[j] <= 8'd255;
                    max_x[j] <= 8'd0;
                    min_y[j] <= 8'd255;
                    max_y[j] <= 8'd0;
                end
                scan_done <= 1'b0;
                copy_done <= 1'b0;
                copy_done_d <= 1'b0;
                box_count <= 10'd1;
                pixel_x <= 8'd0;
                pixel_y <= 8'd0;
                box_write_1_done <= 1'b0;
                //box_write_2_done <= 1'b0;
                box_write_3_done <= 1'b0;
                box_write_4_done <= 1'b0;
                done <= 1'b0;
                boxing_done <= 1'b0;
                read_pixel <= 16'd0;
                cur_x <= 8'd0;
        cur_y <= 8'd0;
            end
            SCAN:begin
                // read label picture from ans_ram
                Ans_CEN <= 1'b0;
                Ans_A <= read_pixel;
                if(read_pixel < 16'd65535)begin
                    read_pixel <= read_pixel + 16'd1;
                end

                if(!Ans_CEN_d)begin
                    // 1. 先做比較（此時 cur_x 和 cur_y 還是當下這個 Pixel 的座標）
                    if(Ans_Q != 32'd0)begin
                        if(cur_x > max_x[Ans_Q[8:0]]) max_x[Ans_Q[8:0]] <= cur_x;
                        if(cur_x < min_x[Ans_Q[8:0]]) min_x[Ans_Q[8:0]] <= cur_x;
                        if(cur_y > max_y[Ans_Q[8:0]]) max_y[Ans_Q[8:0]] <= cur_y;
                        if(cur_y < min_y[Ans_Q[8:0]]) min_y[Ans_Q[8:0]] <= cur_y;
                    end

                    // 2. 更新計數器與座標
                    if(pixel == 16'd65535)begin
                        scan_done <= 1'b1;
                        Ans_CEN <= 1'b1;
                        Ans_A <= 16'd0;
                        pixel <= 16'd0;
                        read_pixel <= 16'd0;
                        cur_x <= 8'd0; // 掃描結束，X 歸零
                        cur_y <= 8'd0; // 掃描結束，Y 歸零
                    end else begin
                        pixel <= pixel + 16'd1;
                        // 二維座標計數邏輯
                        if(cur_x == 8'd255) begin
                            cur_x <= 8'd0;         // 換行：X 歸零
                            cur_y <= cur_y + 8'd1; // 換行：Y 往下走一格
                        end else begin
                            cur_x <= cur_x + 8'd1; // 還沒到行尾，X 繼續往右走
                        end
                    end
                end
            end
            COPY:begin
                // copy all the thing from rom
                Img_CEN <= 1'b0;
                Img_A <= read_pixel;
                if(read_pixel < 16'd65535)begin
                    //Img_A <= read_pixel;
                    read_pixel <= read_pixel + 16'd1;
                end
                if(!Img_CEN_d)begin
                    Ans_CEN <= 1'b0;
                    Ans_WEN <= 1'b0;
                    Ans_A <= pixel;
                    Ans_D <= Img_Q;
                    if(Ans_A == 16'd65534)copy_done <= 1'b1;
                    if(Ans_A == 16'd65535)begin
                        Ans_CEN <= 1'b1;
                        Ans_WEN <= 1'b1;
                        copy_done <= 1'b1;
                        Img_CEN <= 1'b1;
                    end else begin
                        pixel <= pixel + 16'd1;
                    end
                end
            end
            BOXING:begin
                if(box_count <= total_label)begin
                    // box it !!
                    case(box_state)
                        BOX_IDLE:begin
                            pixel_x <= 8'd0;
                            pixel_y <= 8'd0;
                            Ans_CEN <= 1'b1;
                            Ans_WEN <= 1'b1;
                            Ans_A <= 16'd0;
                            box_write_1_done <= 1'b0;
                            //box_write_2_done <= 1'b0;
                            box_write_3_done <= 1'b0;
                            box_write_4_done <= 1'b0;
                        end
                        BOX_INITIAL:begin
                            pixel_x <= min_x[box_count];
                            pixel_y <= min_y[box_count];
                        end
                        // write first row
                        BOX_WRITE_1:begin
                            Ans_CEN <= 1'b0;
                            Ans_WEN <= 1'b0;
                            Ans_A <= {pixel_y,pixel_x};
                            Ans_D <= 32'h0000_FF00;
                            if(pixel_x < max_x[box_count])begin
                                pixel_x <= pixel_x + 8'd1;
                            end else begin
                                box_write_1_done <= 1'b1;
                                pixel_x <= min_x[box_count];
                                pixel_y <= max_y[box_count];
                            end
                        end
                        // write last row
                        BOX_WRITE_2:begin
                            Ans_A <= {pixel_y,pixel_x};
                            Ans_D <= 32'h0000_FF00;
                            if(pixel_x < max_x[box_count])begin
                                pixel_x <= pixel_x + 8'd1;
                            end else begin
                                //box_write_2_done <= 1'b1;
                                pixel_x <= min_x[box_count];
                                pixel_y <= min_y[box_count] + 8'd1;
                            end
                        end
                        // write first column
                        BOX_WRITE_3:begin
                            Ans_A <= {pixel_y,pixel_x};
                            Ans_D <= 32'h0000_FF00;
                            if(pixel_y < (max_y[box_count] - 8'd1))begin
                                pixel_y <= pixel_y + 8'd1;
                            end else begin
                                box_write_3_done <= 1'b1;
                                pixel_x <= max_x[box_count];
                                pixel_y <= min_y[box_count] + 8'd1;
                            end
                        end
                        // write last column
                        BOX_WRITE_4:begin
                            Ans_A <= {pixel_y,pixel_x};
                            Ans_D <= 32'h0000_FF00;
                            if(pixel_y < (max_y[box_count] - 8'd1))begin
                                pixel_y <= pixel_y + 8'd1;
                            end else begin
                                box_write_4_done <= 1'b1;
                            end
                        end
                        BOX_DONE:begin
                            Ans_CEN <= 1'b1;
                            Ans_WEN <= 1'b1;
                            Ans_A <= 16'd0;
                            box_count <= box_count + 10'd1;
                        end
                    endcase
                end else begin
                    boxing_done <= 1'b1;
                end
            end
            DONE:begin
                done <= 1'b1;
            end
        endcase
    end
end

always@(posedge clk or posedge rst)begin
    if(rst)begin
        copy_done_d <= 1'b0;
    end else begin
        copy_done_d <= copy_done;
    end
end


always@(posedge clk or posedge rst)begin
    if(rst)begin
        state <= IDLE;
    end else begin
        state <= next_state;
    end
end

always@(posedge clk or posedge rst)begin
    if(rst)begin
        box_state <= BOX_IDLE;
    end else begin
        box_state <= box_next_state;
    end
end

always@(*)begin
    case(box_state)
        BOX_IDLE:begin
            // 🚨 兩層終極防護：
            // 1. state == BOXING：確保主狀態機到了才開始畫，消滅左上角幽靈線！
            // 2. min <= max：確保這是真實存在的物件，消滅殘缺線條！
            if(state == BOXING) begin
                if(min_x[box_count] <= max_x[box_count] &&
                   min_y[box_count] <= max_y[box_count] &&
                   min_x[box_count] > 8'd0 &&
                   min_y[box_count] > 8'd0 &&
                   max_x[box_count] < 8'd255 &&
                   max_y[box_count] < 8'd255 &&
                   ((max_x[box_count] - min_x[box_count]) >10)&&
                   ((max_y[box_count] - min_y[box_count]) >10))  begin
                    box_next_state = BOX_INITIAL;
                end else begin
                    box_next_state = BOX_DONE; // 碰到邊界或空標籤，直接跳下一個
                end
            end else begin
                box_next_state = BOX_IDLE; // 主狀態還沒到，乖乖原地等待
            end
        end
        BOX_INITIAL:begin
            box_next_state = BOX_WRITE_1;
        end
        BOX_WRITE_1:begin
            if(box_write_1_done)box_next_state = BOX_WRITE_2;
            else box_next_state = BOX_WRITE_1;
        end
        /*BOX_WRITE_2:begin
            if(box_write_2_done)box_next_state = BOX_WRITE_3;
            else box_next_state = BOX_WRITE_2;
        end*/
BOX_WRITE_2:begin
            if(pixel_x == max_x[box_count]) box_next_state = BOX_WRITE_3;
            else box_next_state = BOX_WRITE_2;
        end
        BOX_WRITE_3:begin
            if(box_write_3_done)box_next_state = BOX_WRITE_4;
            else box_next_state = BOX_WRITE_3;
        end
        BOX_WRITE_4:begin
            if(box_write_4_done)box_next_state = BOX_DONE;
            else box_next_state = BOX_WRITE_4;
        end
        BOX_DONE:begin
            box_next_state = BOX_IDLE;
        end
        default:begin
            box_next_state = BOX_IDLE; // 養成好習慣，補上 default 防止 Latch
        end
    endcase
end

always@(*)begin
    case(state)
        IDLE:begin
            if(enable) next_state = SCAN;
            else next_state = IDLE;
        end
        SCAN:begin
            if(pixel == 16'd65535) next_state = COPY;
            else next_state = SCAN;
        end
        COPY:begin
//if(copy_done) next_state = DONE;
            if(copy_done) next_state = BOXING;
            else next_state = COPY;
        end
        BOXING:begin
            if(boxing_done) next_state = DONE;
            else next_state = BOXING;
        end
        DONE:begin
            next_state = IDLE;
        end
    endcase
end

endmodule
